# Generated by Django 4.0.6 on 2022-07-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
