# Generated by Django 4.0.6 on 2022-07-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoApp', '0002_account_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
    ]
