# Generated by Django 4.0.6 on 2022-07-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicoApp', '0003_alter_psychologist_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologist',
            old_name='id_document',
            new_name='id',
        ),
    ]
