# Generated by Django 4.0.6 on 2022-07-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicoApp', '0004_rename_id_document_psychologist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologist',
            old_name='price',
            new_name='consultation_price',
        ),
    ]
