# Generated by Django 4.0.6 on 2022-07-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicoApp', '0005_rename_price_psychologist_consultation_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
