from .accountSerializer import AccountSerializer
from .citySerializer import citySerializer
from .PsychologistSerializer import PsychologistSerializer
from .typeSpecialtySerializer import TypeSpecialtySerializer
